# Generated by Django 4.0.5 on 2022-06-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
